### ISSUE TITLE
Preview link is throwing a Worker Exception

### ISSUE THREAD

**Issue by toklok** [charlespwd/faster#1]
Here is my set up, when I click "Preview" it throws a Error 1101. :(

![image](https://user-images.githubusercontent.com/7063845/113421742-9db38780-9399-11eb-896f-95b986f4c8ca.png)

**Comment by charlespwd** [comment]
TIL '%20' gets decoded by decodeURIComponent into a plus sign. Making it so the CSS selectors were parsed from the query string as "head+>+script[src]..." instead of "head > script[src]..."

Should be good now!
